version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - user-order-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - user-order-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - user-order-network

  order-service:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - user-order-network

volumes:
  postgres_data:

networks:
  user-order-network:
    external: true